#!/usr/bin/env python
# -*- coding:utf-8 -*-

if __name__ == "__main__":
    f1 = open("../data/fixed/train_data_100w.txt","r")
    f2 = open("../data/derived/train_data_2w.txt","w")
    lines = f1.readlines()
    for i in range(34243,34243+20000):
        f2.write(lines[i].strip() + "\n")