#!/usr/bin/env python
# -*- coding:utf-8 -*-

if __name__ == "__main__":
    f1 = open("old.txt","r")
    f2 = open("new.txt","w")
    lines = f1.readlines()
    for i in range(29):
        line = lines[i].strip().split()
        f2.write(line[1] + "\n")